const x = {
  leagues: [
    {
      leagueURL: 'mensopensoccerfall2021',
      leagueName: "Men's Open 7v7 - Fall 2021",
      sport: 'Soccer',
      id: 0
    },
    {
      leagueURL: 'coedsoccerfall2021',
      leagueName: 'Co-Ed Soccer - Fall 2021',
      sport: 'Soccer',
      id: 1
    }
  ],
  teams: [
    {
      teamId: '1',
      teamName: 'Jackson Lions',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 0,
      division: 'A',
      wins: '8',
      losses: '0',
      ties: '0',
      points: '24',
      goalsFor: '67',
      goalsAgainst: '36',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '3',
      teamName: 'Yuhas FC',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 0,
      division: 'A',
      wins: '6',
      losses: '2',
      ties: '0',
      points: '18',
      goalsFor: '58',
      goalsAgainst: '33',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '7',
      teamName: 'Mook Boys  FC',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 0,
      division: 'A',
      wins: '6',
      losses: '2',
      ties: '0',
      points: '18',
      goalsFor: '53',
      goalsAgainst: '33',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '2',
      teamName: 'Net City FC',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 0,
      division: 'A',
      wins: '4',
      losses: '3',
      ties: '1',
      points: '13',
      goalsFor: '32',
      goalsAgainst: '34',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '9',
      teamName: 'Blackbird  FC',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 1,
      division: 'B',
      wins: '4',
      losses: '2',
      ties: '2',
      points: '14',
      goalsFor: '35',
      goalsAgainst: '34',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '5',
      teamName: 'Class on  Grass',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 1,
      division: 'B',
      wins: '4',
      losses: '3',
      ties: '1',
      points: '13',
      goalsFor: '40',
      goalsAgainst: '32',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '14',
      teamName: 'The  Woolley Mammoths',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 1,
      division: 'B',
      wins: '5',
      losses: '3',
      ties: '0',
      points: '15',
      goalsFor: '40',
      goalsAgainst: '29',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '6',
      teamName: 'Liverpool  FC',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 1,
      division: 'B',
      wins: '4',
      losses: '3',
      ties: '1',
      points: '13',
      goalsFor: '45',
      goalsAgainst: '37',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '11',
      teamName: 'Para  Dougie FC',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 2,
      division: 'C',
      wins: '3',
      losses: '4',
      ties: '1',
      points: '10',
      goalsFor: '29',
      goalsAgainst: '30',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '12',
      teamName: 'PSV  Hangover',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 2,
      division: 'C',
      wins: '3',
      losses: '5',
      ties: '0',
      points: '9',
      goalsFor: '35',
      goalsAgainst: '44',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '4',
      teamName: 'Central Jersey No Love Lover Boys',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 2,
      division: 'C',
      wins: '2',
      losses: '5',
      ties: '1',
      points: '7',
      goalsFor: '43',
      goalsAgainst: '46',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '8',
      teamName: 'Victorious  Secret',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 2,
      division: 'C',
      wins: '2',
      losses: '5',
      ties: '1',
      points: '7',
      goalsFor: '29',
      goalsAgainst: '46',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '10',
      teamName: 'Joe F.C.',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 2,
      division: 'C',
      wins: '2',
      losses: '5',
      ties: '1',
      points: '7',
      goalsFor: '25',
      goalsAgainst: '45',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '13',
      teamName: 'Simp City  FC',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 2,
      division: 'C',
      wins: '2',
      losses: '6',
      ties: '0',
      points: '6',
      goalsFor: '24',
      goalsAgainst: '56',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '15',
      teamName: 'Free Agent  FC',
      leagueId: 0,
      league: "Men's Open 7v7 - Fall 2021",
      divisionId: 2,
      division: 'C',
      wins: '0',
      losses: '7',
      ties: '1',
      points: '1',
      goalsFor: '16',
      goalsAgainst: '36',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '2',
      teamName: 'No New Friends',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '8',
      losses: '0',
      ties: '0',
      points: '24',
      goalsFor: '93',
      goalsAgainst: '41',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '1',
      teamName: 'Boring Milners',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '5',
      losses: '2',
      ties: '1',
      points: '16',
      goalsFor: '89',
      goalsAgainst: '70',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '3',
      teamName: 'Threat Level Midnight',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '5',
      losses: '2',
      ties: '1',
      points: '16',
      goalsFor: '54',
      goalsAgainst: '49',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '7',
      teamName: 'Garlic Knots',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '43',
      goalsAgainst: '58',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '9',
      teamName: 'Taco Tuesday',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '74',
      goalsAgainst: '60',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '4',
      teamName: 'White Walkers',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '62',
      goalsAgainst: '69',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '8',
      teamName: "Reese's B Team",
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '3',
      losses: '4',
      ties: '1',
      points: '10',
      goalsFor: '50',
      goalsAgainst: '42',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '10',
      teamName: 'Tiger Balm Tigers FC',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '2',
      losses: '5',
      ties: '1',
      points: '7',
      goalsFor: '43',
      goalsAgainst: '65',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '6',
      teamName: 'Expect The Unexpected',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '2',
      losses: '6',
      ties: '0',
      points: '6',
      goalsFor: '41',
      goalsAgainst: '61',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '5',
      teamName: 'Crabcakes &amp; Futbol',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 0,
      division: 'A',
      wins: '2',
      losses: '6',
      ties: '0',
      points: '6',
      goalsFor: '34',
      goalsAgainst: '49',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '12',
      teamName: 'Farcelona',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 1,
      division: 'B',
      wins: '7',
      losses: '1',
      ties: '0',
      points: '21',
      goalsFor: '83',
      goalsAgainst: '32',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '13',
      teamName: 'FU FC',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 1,
      division: 'B',
      wins: '5',
      losses: '3',
      ties: '0',
      points: '15',
      goalsFor: '59',
      goalsAgainst: '55',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '11',
      teamName: "Andrew's Angels",
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 1,
      division: 'B',
      wins: '4',
      losses: '3',
      ties: '1',
      points: '13',
      goalsFor: '73',
      goalsAgainst: '58',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '17',
      teamName: 'Unprotected Cesc',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 1,
      division: 'B',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '58',
      goalsAgainst: '65',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '18',
      teamName: 'Walnut FC',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 1,
      division: 'B',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '45',
      goalsAgainst: '42',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '15',
      teamName: 'Pepe Grillos',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 1,
      division: 'B',
      wins: '3',
      losses: '4',
      ties: '1',
      points: '10',
      goalsFor: '41',
      goalsAgainst: '55',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '14',
      teamName: 'LORC Of The Rings',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 1,
      division: 'B',
      wins: '3',
      losses: '5',
      ties: '0',
      points: '9',
      goalsFor: '43',
      goalsAgainst: '66',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '16',
      teamName: 'TF Townies',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 1,
      division: 'B',
      wins: '2',
      losses: '6',
      ties: '0',
      points: '6',
      goalsFor: '35',
      goalsAgainst: '50',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '21',
      teamName: "Carney's Pub",
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '6',
      losses: '1',
      ties: '1',
      points: '19',
      goalsFor: '71',
      goalsAgainst: '42',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '24',
      teamName: 'Practice Squad',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '6',
      losses: '2',
      ties: '0',
      points: '18',
      goalsFor: '80',
      goalsAgainst: '59',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '28',
      teamName: 'Staguars',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '5',
      losses: '2',
      ties: '1',
      points: '16',
      goalsFor: '68',
      goalsAgainst: '49',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '23',
      teamName: 'Michelle Canning',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '5',
      losses: '2',
      ties: '1',
      points: '16',
      goalsFor: '74',
      goalsAgainst: '59',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '20',
      teamName: 'Blue Moose',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '5',
      losses: '3',
      ties: '0',
      points: '15',
      goalsFor: '95',
      goalsAgainst: '74',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '26',
      teamName: 'Schrute Farms',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '50',
      goalsAgainst: '40',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '19',
      teamName: 'Big Dribble Energy',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '56',
      goalsAgainst: '74',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '27',
      teamName: 'Shore Perfect',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '82',
      goalsAgainst: '54',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '29',
      teamName: 'Wiz KhaFIFA',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '3',
      losses: '5',
      ties: '0',
      points: '9',
      goalsFor: '56',
      goalsAgainst: '75',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '22',
      teamName: 'Lickity Splits',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '2',
      losses: '6',
      ties: '0',
      points: '6',
      goalsFor: '66',
      goalsAgainst: '101',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '25',
      teamName: 'Purple Cobras',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 2,
      division: 'C',
      wins: '0',
      losses: '7',
      ties: '1',
      points: '1',
      goalsFor: '56',
      goalsAgainst: '80',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '31',
      teamName: 'Average Joes',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '6',
      losses: '1',
      ties: '1',
      points: '19',
      goalsFor: '75',
      goalsAgainst: '70',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '33',
      teamName: 'Goals Gone Wild',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '6',
      losses: '2',
      ties: '0',
      points: '18',
      goalsFor: '108',
      goalsAgainst: '62',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '35',
      teamName: 'Hawks',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '5',
      losses: '3',
      ties: '0',
      points: '15',
      goalsFor: '55',
      goalsAgainst: '47',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '36',
      teamName: 'Inferno FC',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '3',
      losses: '2',
      ties: '3',
      points: '12',
      goalsFor: '70',
      goalsAgainst: '85',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '34',
      teamName: 'Goats FC',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '4',
      losses: '4',
      ties: '0',
      points: '12',
      goalsFor: '96',
      goalsAgainst: '109',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '30',
      teamName: '2 Goals 1 Cup',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '3',
      losses: '5',
      ties: '0',
      points: '9',
      goalsFor: '87',
      goalsAgainst: '91',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '39',
      teamName: 'The Scousers',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '2',
      losses: '6',
      ties: '0',
      points: '6',
      goalsFor: '40',
      goalsAgainst: '65',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '37',
      teamName: 'Kankle Kickers',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '2',
      losses: '6',
      ties: '0',
      points: '6',
      goalsFor: '62',
      goalsAgainst: '79',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '32',
      teamName: 'Brute Force',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '0',
      losses: '6',
      ties: '2',
      points: '2',
      goalsFor: '60',
      goalsAgainst: '97',
      gamesPlayed: '8',
      games: []
    },
    {
      teamId: '38',
      teamName: 'Remorseless',
      leagueId: 1,
      league: 'Co-Ed Soccer - Fall 2021',
      divisionId: 3,
      division: 'D',
      wins: '0',
      losses: '6',
      ties: '2',
      points: '2',
      goalsFor: '74',
      goalsAgainst: '105',
      gamesPlayed: '8',
      games: []
    }
  ],
  games: [
    {
      gameId: 1,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 11,
      team1Name: 'Para  Dougie FC',
      team2Id: 13,
      team2Name: 'Simp City  FC',
      time: '6:30 PM',
      date: '8-Sep',
      week: 1,
      timestamp: 2021-09-08T22:30:00.000Z,
      dateStr: 'Wednesday, September 8'
    },
    {
      gameId: 2,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 4,
      team1Name: 'Central Jersey No Love Lover Boys',
      team2Id: 7,
      team2Name: 'Mook Boys  FC',
      time: '6:30 PM',
      date: '15-Sep',
      week: 2,
      timestamp: 2021-09-15T22:30:00.000Z,
      dateStr: 'Wednesday, September 15'
    },
    {
      gameId: 3,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 2,
      team1Name: 'Net City FC',
      team2Id: 8,
      team2Name: 'Victorious  Secret',
      time: '6:30 PM',
      date: '22-Sep',
      week: 3,
      timestamp: 2021-09-22T22:30:00.000Z,
      dateStr: 'Wednesday, September 22'
    },
    {
      gameId: 4,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 4,
      team1Name: 'Central Jersey No Love Lover Boys',
      team2Id: 10,
      team2Name: 'Joe F.C.',
      time: '7:20 PM',
      date: '8-Sep',
      week: 1,
      timestamp: 2021-09-08T23:20:00.000Z,
      dateStr: 'Wednesday, September 8'
    },
    {
      gameId: 5,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 6,
      team1Name: 'Liverpool  FC',
      team2Id: 8,
      team2Name: 'Victorious  Secret',
      time: '7:20 PM',
      date: '15-Sep',
      week: 2,
      timestamp: 2021-09-15T23:20:00.000Z,
      dateStr: 'Wednesday, September 15'
    },
    {
      gameId: 6,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 3,
      team1Name: 'Yuhas FC',
      team2Id: 6,
      team2Name: 'Liverpool  FC',
      time: '7:20 PM',
      date: '22-Sep',
      week: 3,
      timestamp: 2021-09-22T23:20:00.000Z,
      dateStr: 'Wednesday, September 22'
    },
    {
      gameId: 7,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 1,
      team1Name: 'Jackson Lions',
      team2Id: 8,
      team2Name: 'Victorious  Secret',
      time: '8:10 PM',
      date: '8-Sep',
      week: 1,
      timestamp: 2021-09-09T00:10:00.000Z,
      dateStr: 'Wednesday, September 8'
    },
    {
      gameId: 8,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 1,
      team1Name: 'Jackson Lions',
      team2Id: 3,
      team2Name: 'Yuhas FC',
      time: '8:10 PM',
      date: '15-Sep',
      week: 2,
      timestamp: 2021-09-16T00:10:00.000Z,
      dateStr: 'Wednesday, September 15'
    },
    {
      gameId: 9,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 9,
      team1Name: 'Blackbird  FC',
      team2Id: 10,
      team2Name: 'Joe F.C.',
      time: '8:10 PM',
      date: '22-Sep',
      week: 3,
      timestamp: 2021-09-23T00:10:00.000Z,
      dateStr: 'Wednesday, September 22'
    },
    {
      gameId: 10,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 5,
      team1Name: 'Class on  Grass',
      team2Id: 9,
      team2Name: 'Blackbird  FC',
      time: '9:00 PM',
      date: '8-Sep',
      week: 1,
      timestamp: 2021-09-09T01:00:00.000Z,
      dateStr: 'Wednesday, September 8'
    },
    {
      gameId: 11,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 10,
      team1Name: 'Joe F.C.',
      team2Id: 15,
      team2Name: 'Free Agent  FC',
      time: '9:00 PM',
      date: '15-Sep',
      week: 2,
      timestamp: 2021-09-16T01:00:00.000Z,
      dateStr: 'Wednesday, September 15'
    },
    {
      gameId: 12,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 13,
      team1Name: 'Simp City  FC',
      team2Id: 15,
      team2Name: 'Free Agent  FC',
      time: '9:00 PM',
      date: '22-Sep',
      week: 3,
      timestamp: 2021-09-23T01:00:00.000Z,
      dateStr: 'Wednesday, September 22'
    },
    {
      gameId: 13,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 6,
      team1Name: 'Liverpool  FC',
      team2Id: 7,
      team2Name: 'Mook Boys  FC',
      time: '9:50 PM',
      date: '8-Sep',
      week: 1,
      timestamp: 2021-09-09T01:50:00.000Z,
      dateStr: 'Wednesday, September 8'
    },
    {
      gameId: 14,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 2,
      team1Name: 'Net City FC',
      team2Id: 5,
      team2Name: 'Class on  Grass',
      time: '9:50 PM',
      date: '15-Sep',
      week: 2,
      timestamp: 2021-09-16T01:50:00.000Z,
      dateStr: 'Wednesday, September 15'
    },
    {
      gameId: 15,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 4,
      team1Name: 'Central Jersey No Love Lover Boys',
      team2Id: 5,
      team2Name: 'Class on  Grass',
      time: '9:50 PM',
      date: '22-Sep',
      week: 3,
      timestamp: 2021-09-23T01:50:00.000Z,
      dateStr: 'Wednesday, September 22'
    },
    {
      gameId: 16,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 12,
      team1Name: 'PSV  Hangover',
      team2Id: 14,
      team2Name: 'The  Woolley Mammoths',
      time: '10:40 PM',
      date: '8-Sep',
      week: 1,
      timestamp: 2021-09-09T02:40:00.000Z,
      dateStr: 'Wednesday, September 8'
    },
    {
      gameId: 17,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 9,
      team1Name: 'Blackbird  FC',
      team2Id: 13,
      team2Name: 'Simp City  FC',
      time: '10:40 PM',
      date: '15-Sep',
      week: 2,
      timestamp: 2021-09-16T02:40:00.000Z,
      dateStr: 'Wednesday, September 15'
    },
    {
      gameId: 18,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 1,
      team1Name: 'Jackson Lions',
      team2Id: 7,
      team2Name: 'Mook Boys  FC',
      time: '10:40 PM',
      date: '22-Sep',
      week: 3,
      timestamp: 2021-09-23T02:40:00.000Z,
      dateStr: 'Wednesday, September 22'
    },
    {
      gameId: 19,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: NaN,
      team1Name: undefined,
      team2Id: undefined,
      team2Name: undefined,
      time: '&nbsp;',
      date: '9-Sep',
      week: 1,
      timestamp: Invalid Date,
      dateStr: 'Invalid Date'
    },
    {
      gameId: 20,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 11,
      team1Name: 'Para  Dougie FC',
      team2Id: 12,
      team2Name: 'PSV  Hangover',
      time: '9:00 PM',
      date: '16-Sep',
      week: 2,
      timestamp: 2021-09-17T01:00:00.000Z,
      dateStr: 'Thursday, September 16'
    },
    {
      gameId: 21,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 11,
      team1Name: 'Para  Dougie FC',
      team2Id: 14,
      team2Name: 'The  Woolley Mammoths',
      time: '9:50 PM',
      date: '23-Sep',
      week: 3,
      timestamp: 2021-09-24T01:50:00.000Z,
      dateStr: 'Thursday, September 23'
    },
    {
      gameId: 22,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 1,
      team1Name: 'Jackson Lions',
      team2Id: 5,
      team2Name: 'Class on  Grass',
      time: '6:30 PM',
      date: '29-Sep',
      week: 4,
      timestamp: 2021-09-29T22:30:00.000Z,
      dateStr: 'Wednesday, September 29'
    },
    {
      gameId: 23,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 14,
      team1Name: 'The  Woolley Mammoths',
      team2Id: 15,
      team2Name: 'Free Agent  FC',
      time: '6:30 PM',
      date: '6-Oct',
      week: 5,
      timestamp: 2021-10-06T22:30:00.000Z,
      dateStr: 'Wednesday, October 6'
    },
    {
      gameId: 24,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 12,
      team1Name: 'PSV  Hangover',
      team2Id: 15,
      team2Name: 'Free Agent  FC',
      time: '6:30 PM',
      date: '13-Oct',
      week: 6,
      timestamp: 2021-10-13T22:30:00.000Z,
      dateStr: 'Wednesday, October 13'
    },
    {
      gameId: 25,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 8,
      team1Name: 'Victorious  Secret',
      team2Id: 9,
      team2Name: 'Blackbird  FC',
      time: '7:20 PM',
      date: '29-Sep',
      week: 4,
      timestamp: 2021-09-29T23:20:00.000Z,
      dateStr: 'Wednesday, September 29'
    },
    {
      gameId: 26,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 12,
      team1Name: 'PSV  Hangover',
      team2Id: 13,
      team2Name: 'Simp City  FC',
      time: '7:20 PM',
      date: '6-Oct',
      week: 5,
      timestamp: 2021-10-06T23:20:00.000Z,
      dateStr: 'Wednesday, October 6'
    },
    {
      gameId: 27,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 5,
      team1Name: 'Class on  Grass',
      team2Id: 14,
      team2Name: 'The  Woolley Mammoths',
      time: '7:20 PM',
      date: '13-Oct',
      week: 6,
      timestamp: 2021-10-13T23:20:00.000Z,
      dateStr: 'Wednesday, October 13'
    },
    {
      gameId: 28,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 4,
      team1Name: 'Central Jersey No Love Lover Boys',
      team2Id: 14,
      team2Name: 'The  Woolley Mammoths',
      time: '8:10 PM',
      date: '29-Sep',
      week: 4,
      timestamp: 2021-09-30T00:10:00.000Z,
      dateStr: 'Wednesday, September 29'
    },
    {
      gameId: 29,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 5,
      team1Name: 'Class on  Grass',
      team2Id: 6,
      team2Name: 'Liverpool  FC',
      time: '8:10 PM',
      date: '6-Oct',
      week: 5,
      timestamp: 2021-10-07T00:10:00.000Z,
      dateStr: 'Wednesday, October 6'
    },
    {
      gameId: 30,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 2,
      team1Name: 'Net City FC',
      team2Id: 3,
      team2Name: 'Yuhas FC',
      time: '8:10 PM',
      date: '13-Oct',
      week: 6,
      timestamp: 2021-10-14T00:10:00.000Z,
      dateStr: 'Wednesday, October 13'
    },
    {
      gameId: 31,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 3,
      team1Name: 'Yuhas FC',
      team2Id: 7,
      team2Name: 'Mook Boys  FC',
      time: '9:00 PM',
      date: '29-Sep',
      week: 4,
      timestamp: 2021-09-30T01:00:00.000Z,
      dateStr: 'Wednesday, September 29'
    },
    {
      gameId: 32,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 1,
      team1Name: 'Jackson Lions',
      team2Id: 2,
      team2Name: 'Net City FC',
      time: '9:00 PM',
      date: '6-Oct',
      week: 5,
      timestamp: 2021-10-07T01:00:00.000Z,
      dateStr: 'Wednesday, October 6'
    },
    {
      gameId: 33,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 6,
      team1Name: 'Liverpool  FC',
      team2Id: 13,
      team2Name: 'Simp City  FC',
      time: '9:00 PM',
      date: '13-Oct',
      week: 6,
      timestamp: 2021-10-14T01:00:00.000Z,
      dateStr: 'Wednesday, October 13'
    },
    {
      gameId: 34,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 10,
      team1Name: 'Joe F.C.',
      team2Id: 12,
      team2Name: 'PSV  Hangover',
      time: '9:50 PM',
      date: '29-Sep',
      week: 4,
      timestamp: 2021-09-30T01:50:00.000Z,
      dateStr: 'Wednesday, September 29'
    },
    {
      gameId: 35,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 7,
      team1Name: 'Mook Boys  FC',
      team2Id: 8,
      team2Name: 'Victorious  Secret',
      time: '9:50 PM',
      date: '6-Oct',
      week: 5,
      timestamp: 2021-10-07T01:50:00.000Z,
      dateStr: 'Wednesday, October 6'
    },
    {
      gameId: 36,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 4,
      team1Name: 'Central Jersey No Love Lover Boys',
      team2Id: 9,
      team2Name: 'Blackbird  FC',
      time: '9:50 PM',
      date: '13-Oct',
      week: 6,
      timestamp: 2021-10-14T01:50:00.000Z,
      dateStr: 'Wednesday, October 13'
    },
    {
      gameId: 37,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 2,
      team1Name: 'Net City FC',
      team2Id: 6,
      team2Name: 'Liverpool  FC',
      time: '10:40 PM',
      date: '29-Sep',
      week: 4,
      timestamp: 2021-09-30T02:40:00.000Z,
      dateStr: 'Wednesday, September 29'
    },
    {
      gameId: 38,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 3,
      team1Name: 'Yuhas FC',
      team2Id: 4,
      team2Name: 'Central Jersey No Love Lover Boys',
      time: '10:40 PM',
      date: '6-Oct',
      week: 5,
      timestamp: 2021-10-07T02:40:00.000Z,
      dateStr: 'Wednesday, October 6'
    },
    {
      gameId: 39,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 8,
      team1Name: 'Victorious  Secret',
      team2Id: 10,
      team2Name: 'Joe F.C.',
      time: '10:40 PM',
      date: '13-Oct',
      week: 6,
      timestamp: 2021-10-14T02:40:00.000Z,
      dateStr: 'Wednesday, October 13'
    },
    {
      gameId: 40,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 11,
      team1Name: 'Para  Dougie FC',
      team2Id: 15,
      team2Name: 'Free Agent  FC',
      time: '9:50 PM',
      date: '30-Sep',
      week: 4,
      timestamp: 2021-10-01T01:50:00.000Z,
      dateStr: 'Thursday, September 30'
    },
    {
      gameId: 41,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 9,
      team1Name: 'Blackbird  FC',
      team2Id: 11,
      team2Name: 'Para  Dougie FC',
      time: '9:00 PM',
      date: '7-Oct',
      week: 5,
      timestamp: 2021-10-08T01:00:00.000Z,
      dateStr: 'Thursday, October 7'
    },
    {
      gameId: 42,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 7,
      team1Name: 'Mook Boys  FC',
      team2Id: 11,
      team2Name: 'Para  Dougie FC',
      time: '9:00 PM',
      date: '14-Oct',
      week: 6,
      timestamp: 2021-10-15T01:00:00.000Z,
      dateStr: 'Thursday, October 14'
    },
    {
      gameId: 43,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 10,
      team1Name: 'Joe F.C.',
      team2Id: 14,
      team2Name: 'The  Woolley Mammoths',
      time: '6:30 PM',
      date: '20-Oct',
      week: 7,
      timestamp: 2021-10-20T22:30:00.000Z,
      dateStr: 'Wednesday, October 20'
    },
    {
      gameId: 44,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 3,
      team1Name: 'Yuhas FC',
      team2Id: 5,
      team2Name: 'Class on  Grass',
      time: '6:30 PM',
      date: '27-Oct',
      week: 8,
      timestamp: 2021-10-27T22:30:00.000Z,
      dateStr: 'Wednesday, October 27'
    },
    {
      gameId: 45,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 3,
      team1Name: 'Yuhas FC',
      team2Id: 8,
      team2Name: 'Victorious  Secret',
      time: '6:30 PM',
      date: '3-Nov',
      week: 9,
      timestamp: 2021-11-03T22:30:00.000Z,
      dateStr: 'Wednesday, November 3'
    },
    {
      gameId: 46,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 6,
      team1Name: 'Liverpool  FC',
      team2Id: 12,
      team2Name: 'PSV  Hangover',
      time: '7:20 PM',
      date: '20-Oct',
      week: 7,
      timestamp: 2021-10-20T23:20:00.000Z,
      dateStr: 'Wednesday, October 20'
    },
    {
      gameId: 47,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 1,
      team1Name: 'Jackson Lions',
      team2Id: 2,
      team2Name: 'Net City FC',
      time: '7:20 PM',
      date: '27-Oct',
      week: 8,
      timestamp: 2021-10-27T23:20:00.000Z,
      dateStr: 'Wednesday, October 27'
    },
    {
      gameId: 48,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 2,
      team1Name: 'Net City FC',
      team2Id: 14,
      team2Name: 'The  Woolley Mammoths',
      time: '7:20 PM',
      date: '3-Nov',
      week: 9,
      timestamp: 2021-11-03T23:20:00.000Z,
      dateStr: 'Wednesday, November 3'
    },
    {
      gameId: 49,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 7,
      team1Name: 'Mook Boys  FC',
      team2Id: 9,
      team2Name: 'Blackbird  FC',
      time: '8:10 PM',
      date: '20-Oct',
      week: 7,
      timestamp: 2021-10-21T00:10:00.000Z,
      dateStr: 'Wednesday, October 20'
    },
    {
      gameId: 50,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 9,
      team1Name: 'Blackbird  FC',
      team2Id: 15,
      team2Name: 'Free Agent  FC',
      time: '8:10 PM',
      date: '27-Oct',
      week: 8,
      timestamp: 2021-10-28T00:10:00.000Z,
      dateStr: 'Wednesday, October 27'
    },
    {
      gameId: 51,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 6,
      team1Name: 'Liverpool  FC',
      team2Id: 15,
      team2Name: 'Free Agent  FC',
      time: '8:10 PM',
      date: '3-Nov',
      week: 9,
      timestamp: 2021-11-04T00:10:00.000Z,
      dateStr: 'Wednesday, November 3'
    },
    {
      gameId: 52,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 8,
      team1Name: 'Victorious  Secret',
      team2Id: 15,
      team2Name: 'Free Agent  FC',
      time: '9:00 PM',
      date: '20-Oct',
      week: 7,
      timestamp: 2021-10-21T01:00:00.000Z,
      dateStr: 'Wednesday, October 20'
    },
    {
      gameId: 53,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 7,
      team1Name: 'Mook Boys  FC',
      team2Id: 12,
      team2Name: 'PSV  Hangover',
      time: '9:00 PM',
      date: '27-Oct',
      week: 8,
      timestamp: 2021-10-28T01:00:00.000Z,
      dateStr: 'Wednesday, October 27'
    },
    {
      gameId: 54,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 1,
      team1Name: 'Jackson Lions',
      team2Id: 4,
      team2Name: 'Central Jersey No Love Lover Boys',
      time: '9:00 PM',
      date: '3-Nov',
      week: 9,
      timestamp: 2021-11-04T01:00:00.000Z,
      dateStr: 'Wednesday, November 3'
    },
    {
      gameId: 55,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 1,
      team1Name: 'Jackson Lions',
      team2Id: 3,
      team2Name: 'Yuhas FC',
      time: '9:50 PM',
      date: '20-Oct',
      week: 7,
      timestamp: 2021-10-21T01:50:00.000Z,
      dateStr: 'Wednesday, October 20'
    },
    {
      gameId: 56,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 13,
      team1Name: 'Simp City  FC',
      team2Id: 14,
      team2Name: 'The  Woolley Mammoths',
      time: '9:50 PM',
      date: '27-Oct',
      week: 8,
      timestamp: 2021-10-28T01:50:00.000Z,
      dateStr: 'Wednesday, October 27'
    },
    {
      gameId: 57,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 10,
      team1Name: 'Joe F.C.',
      team2Id: 13,
      team2Name: 'Simp City  FC',
      time: '9:50 PM',
      date: '3-Nov',
      week: 9,
      timestamp: 2021-11-04T01:50:00.000Z,
      dateStr: 'Wednesday, November 3'
    },
    {
      gameId: 58,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 5,
      team1Name: 'Class on  Grass',
      team2Id: 13,
      team2Name: 'Simp City  FC',
      time: '10:40 PM',
      date: '20-Oct',
      week: 7,
      timestamp: 2021-10-21T02:40:00.000Z,
      dateStr: 'Wednesday, October 20'
    },
    {
      gameId: 59,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 2,
      team1Name: 'Net City FC',
      team2Id: 4,
      team2Name: 'Central Jersey No Love Lover Boys',
      time: '9:00 PM',
      date: '21-Oct',
      week: 7,
      timestamp: 2021-10-22T01:00:00.000Z,
      dateStr: 'Thursday, October 21'
    },
    {
      gameId: 60,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 10,
      team1Name: 'Joe F.C.',
      team2Id: 11,
      team2Name: 'Para  Dougie FC',
      time: '9:00 PM',
      date: '28-Oct',
      week: 8,
      timestamp: 2021-10-29T01:00:00.000Z,
      dateStr: 'Thursday, October 28'
    },
    {
      gameId: 61,
      leagueId: 0,
      leagueName: "Men's Open 7v7 - Fall 2021",
      team1Id: 11,
      team1Name: 'Para  Dougie FC',
      team2Id: 12,
      team2Name: 'PSV  Hangover',
      time: '9:50 PM',
      date: '4-Nov',
      week: 9,
      timestamp: 2021-11-05T01:50:00.000Z,
      dateStr: 'Thursday, November 4'
    },
    {
      gameId: 1,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 20,
      team1Name: 'Blue Moose',
      team2Id: 34,
      team2Name: 'Goats FC',
      time: '2:00 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-12T18:00:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 2,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 20,
      team1Name: 'Blue Moose',
      team2Id: 32,
      team2Name: 'Brute Force',
      time: '2:00 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-19T18:00:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 3,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 29,
      team1Name: 'Wiz KhaFIFA',
      team2Id: 30,
      team2Name: '2 Goals 1 Cup',
      time: '2:50 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-12T18:50:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 4,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 3,
      team1Name: 'Threat Level Midnight',
      team2Id: 4,
      team2Name: 'White Walkers',
      time: '2:50 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-19T18:50:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 5,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 32,
      team1Name: 'Brute Force',
      team2Id: 38,
      team2Name: 'Remorseless',
      time: '3:40 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-12T19:40:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 6,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 5,
      team1Name: 'Crabcakes &amp; Futbol',
      team2Id: 12,
      team2Name: 'Farcelona',
      time: '3:40 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-19T19:40:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 7,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 22,
      team1Name: 'Lickity Splits',
      team2Id: 24,
      team2Name: 'Practice Squad',
      time: '4:30 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-12T20:30:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 8,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 6,
      team1Name: 'Expect The Unexpected',
      team2Id: 10,
      team2Name: 'Tiger Balm Tigers FC',
      time: '4:30 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-19T20:30:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 9,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 16,
      team1Name: 'TF Townies',
      team2Id: 26,
      team2Name: 'Schrute Farms',
      time: '5:20 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-12T21:20:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 10,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 18,
      team1Name: 'Walnut FC',
      team2Id: 26,
      team2Name: 'Schrute Farms',
      time: '5:20 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-19T21:20:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 11,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 6,
      team1Name: 'Expect The Unexpected',
      team2Id: 7,
      team2Name: 'Garlic Knots',
      time: '6:10 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-12T22:10:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 12,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 25,
      team1Name: 'Purple Cobras',
      team2Id: 29,
      team2Name: 'Wiz KhaFIFA',
      time: '6:10 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-19T22:10:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 13,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 11,
      team1Name: "Andrew's Angels",
      team2Id: 14,
      team2Name: 'LORC Of The Rings',
      time: '7:00 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-12T23:00:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 14,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 11,
      team1Name: "Andrew's Angels",
      team2Id: 13,
      team2Name: 'FU FC',
      time: '7:00 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-19T23:00:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 15,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 5,
      team1Name: 'Crabcakes &amp; Futbol',
      team2Id: 10,
      team2Name: 'Tiger Balm Tigers FC',
      time: '7:50 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-12T23:50:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 16,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 31,
      team1Name: 'Average Joes',
      team2Id: 34,
      team2Name: 'Goats FC',
      time: '7:50 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-19T23:50:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 17,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 23,
      team1Name: 'Michelle Canning',
      team2Id: 35,
      team2Name: 'Hawks',
      time: '8:40 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-13T00:40:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 18,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 27,
      team1Name: 'Shore Perfect',
      team2Id: 39,
      team2Name: 'The Scousers',
      time: '8:40 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-20T00:40:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 19,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 28,
      team1Name: 'Staguars',
      team2Id: 39,
      team2Name: 'The Scousers',
      time: '9:30 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-13T01:30:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 20,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 36,
      team1Name: 'Inferno FC',
      team2Id: 38,
      team2Name: 'Remorseless',
      time: '9:30 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-20T01:30:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 21,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 27,
      team1Name: 'Shore Perfect',
      team2Id: 33,
      team2Name: 'Goals Gone Wild',
      time: '10:20 PM',
      date: '12-Sep',
      week: 2,
      timestamp: 2021-09-13T02:20:00.000Z,
      dateStr: 'Sunday, September 12'
    },
    {
      gameId: 22,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 8,
      team1Name: "Reese's B Team",
      team2Id: 14,
      team2Name: 'LORC Of The Rings',
      time: '10:20 PM',
      date: '19-Sep',
      week: 3,
      timestamp: 2021-09-20T02:20:00.000Z,
      dateStr: 'Sunday, September 19'
    },
    {
      gameId: 23,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 15,
      team1Name: 'Pepe Grillos',
      team2Id: 18,
      team2Name: 'Walnut FC',
      time: '7:20 PM',
      date: '7-Sep',
      week: 1,
      timestamp: 2021-09-07T23:20:00.000Z,
      dateStr: 'Tuesday, September 7'
    },
    {
      gameId: 24,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 21,
      team1Name: "Carney's Pub",
      team2Id: 37,
      team2Name: 'Kankle Kickers',
      time: '6:30 PM',
      date: '14-Sep',
      week: 2,
      timestamp: 2021-09-14T22:30:00.000Z,
      dateStr: 'Tuesday, September 14'
    },
    {
      gameId: 25,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 7,
      team1Name: 'Garlic Knots',
      team2Id: 9,
      team2Name: 'Taco Tuesday',
      time: '6:30 PM',
      date: '21-Sep',
      week: 3,
      timestamp: 2021-09-21T22:30:00.000Z,
      dateStr: 'Tuesday, September 21'
    },
    {
      gameId: 26,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 1,
      team1Name: 'Boring Milners',
      team2Id: 2,
      team2Name: 'No New Friends',
      time: '8:10 PM',
      date: '7-Sep',
      week: 1,
      timestamp: 2021-09-08T00:10:00.000Z,
      dateStr: 'Tuesday, September 7'
    },
    {
      gameId: 27,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 1,
      team1Name: 'Boring Milners',
      team2Id: 4,
      team2Name: 'White Walkers',
      time: '7:20 PM',
      date: '14-Sep',
      week: 2,
      timestamp: 2021-09-14T23:20:00.000Z,
      dateStr: 'Tuesday, September 14'
    },
    {
      gameId: 28,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 21,
      team1Name: "Carney's Pub",
      team2Id: 35,
      team2Name: 'Hawks',
      time: '7:20 PM',
      date: '21-Sep',
      week: 3,
      timestamp: 2021-09-21T23:20:00.000Z,
      dateStr: 'Tuesday, September 21'
    },
    {
      gameId: 29,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 12,
      team1Name: 'Farcelona',
      team2Id: 17,
      team2Name: 'Unprotected Cesc',
      time: '9:00 PM',
      date: '7-Sep',
      week: 1,
      timestamp: 2021-09-08T01:00:00.000Z,
      dateStr: 'Tuesday, September 7'
    },
    {
      gameId: 30,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 2,
      team1Name: 'No New Friends',
      team2Id: 3,
      team2Name: 'Threat Level Midnight',
      time: '8:10 PM',
      date: '14-Sep',
      week: 2,
      timestamp: 2021-09-15T00:10:00.000Z,
      dateStr: 'Tuesday, September 14'
    },
    {
      gameId: 31,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 15,
      team1Name: 'Pepe Grillos',
      team2Id: 17,
      team2Name: 'Unprotected Cesc',
      time: '8:10 PM',
      date: '21-Sep',
      week: 3,
      timestamp: 2021-09-22T00:10:00.000Z,
      dateStr: 'Tuesday, September 21'
    },
    {
      gameId: 32,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 8,
      team1Name: "Reese's B Team",
      team2Id: 9,
      team2Name: 'Taco Tuesday',
      time: '9:50 PM',
      date: '7-Sep',
      week: 1,
      timestamp: 2021-09-08T01:50:00.000Z,
      dateStr: 'Tuesday, September 7'
    },
    {
      gameId: 33,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 13,
      team1Name: 'FU FC',
      team2Id: 31,
      team2Name: 'Average Joes',
      time: '9:00 PM',
      date: '14-Sep',
      week: 2,
      timestamp: 2021-09-15T01:00:00.000Z,
      dateStr: 'Tuesday, September 14'
    },
    {
      gameId: 34,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 23,
      team1Name: 'Michelle Canning',
      team2Id: 37,
      team2Name: 'Kankle Kickers',
      time: '9:00 PM',
      date: '21-Sep',
      week: 3,
      timestamp: 2021-09-22T01:00:00.000Z,
      dateStr: 'Tuesday, September 21'
    },
    {
      gameId: 35,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 19,
      team1Name: 'Big Dribble Energy',
      team2Id: 25,
      team2Name: 'Purple Cobras',
      time: '9:50 PM',
      date: '14-Sep',
      week: 2,
      timestamp: 2021-09-15T01:50:00.000Z,
      dateStr: 'Tuesday, September 14'
    },
    {
      gameId: 36,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 24,
      team1Name: 'Practice Squad',
      team2Id: 28,
      team2Name: 'Staguars',
      time: '9:50 PM',
      date: '21-Sep',
      week: 3,
      timestamp: 2021-09-22T01:50:00.000Z,
      dateStr: 'Tuesday, September 21'
    },
    {
      gameId: 37,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 12,
      team1Name: 'Farcelona',
      team2Id: 18,
      team2Name: 'Walnut FC',
      time: '2:00 PM',
      date: '26-Sep',
      week: 4,
      timestamp: 2021-09-26T18:00:00.000Z,
      dateStr: 'Sunday, September 26'
    },
    {
      gameId: 38,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 4,
      team1Name: 'White Walkers',
      team2Id: 6,
      team2Name: 'Expect The Unexpected',
      time: '2:20 PM',
      date: '3-Oct',
      week: 5,
      timestamp: 2021-10-03T18:20:00.000Z,
      dateStr: 'Sunday, October 3'
    },
    {
      gameId: 39,
      leagueId: 1,
      leagueName: 'Co-Ed Soccer - Fall 2021',
      team1Id: 7,
      team1Name: 'Garlic Knots',
      team2Id: 10,
      team2Name: 'Tiger Balm Tigers FC',
      time: '2:20 PM',
      date: '10-Oct',
      week: 6,
      timestamp: 2021-10-10T18:20:00.000Z,
      dateStr: 'Sunday, October 10'
    },
    ... 118 more items
  ]
}
